name: release

on:
    push:
        tags:
            - "v*"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v3
              with:
                  version: ^8
            - uses: actions/setup-node@v4
              with:
                  node-version: current
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile
            - name: last time test
              run: pnpm test
            - name: building
              run: pnpm build

    publishNpm:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v3
              with:
                  version: ^8
            - uses: actions/setup-node@v4
              with:
                  node-version: current
                  cache: "pnpm"
            # - name: publish to npm
            #   run: pnpm publish
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publishJsr:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v3
              with:
                  version: ^8
            - uses: actions/setup-node@v4
              with:
                  node-version: current
                  cache: "pnpm"
            - name: publish to JSR
              run: pnpm dlx jsr publish --allow-slow-types
