name: test

# on: [push, workflow_dispatch]
on:
    push:
        branches:
            - "*"

jobs:
    Vitest:
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: ^8
            - uses: actions/setup-node@v4
              with:
                  node-version: current
                  cache: "pnpm"
            - run: pnpm install
            - run: pnpm test
